version: '3'

services:
  api:
    build: ./api
    volumes:
      - ./api:/var/www/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command:
      sh -c 'npm i && node server.js'