version: '3'

services:
  db:
    image: mvertes/alpine-mongo
    container_name: guestbook_mongo
    volumes:
      - guestbook_mongodb:/data/db
    expose:
      - 27017
  api:
    build: ./api
    volumes:
      - ./api:/var/www/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://guestbook_mongo:27017/guestbook
    depends_on:
      - db
    command:
      sh -c 'npm i && node server.js'

volumes:
  guestbook_mongodb: